# Generated by Django 5.0.7 on 2024-07-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boarditem',
            name='username',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
