# Generated by Django 5.0.7 on 2024-08-02 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0002_customuser_firstname_alter_customuser_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='firstname',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
    ]
