# Generated by Django 5.0.7 on 2024-07-24 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0002_boarditem_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boarditem',
            name='username',
        ),
    ]
