# Generated by Django 5.0.7 on 2024-08-02 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0003_remove_customuser_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
