# Generated by Django 5.0.7 on 2024-08-02 01:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0004_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boarditem',
            name='assignedTo',
            field=models.ManyToManyField(blank=True, related_name='assigned_boarditems', to=settings.AUTH_USER_MODEL),
        ),
    ]
